FROM atendai/evolution-api:v1.8.2

ENV PORT=10000
ENV SERVER_PORT=10000

# DESLIGA TUDO O QUE PESA NO LOGIN
ENV DATABASE_TYPE=sqlite
ENV DATABASE_SAVE_DATA_INSTANCE=true
ENV DATABASE_SAVE_DATA_CHATS=false
ENV DATABASE_SAVE_DATA_CONTACTS=false
ENV DATABASE_SAVE_DATA_MESSAGES=false
ENV DATABASE_SAVE_DATA_BAILEYS_CHATS=false
ENV DATABASE_SAVE_DATA_BAILEYS_CONTACTS=false

# BLOQUEIA SINCRONIZAÇÃO DE MENSAGENS ANTIGAS (O que faz o celular travar)
ENV CONFIG_SESSION_CONTROL_HANDLERS_MESSAGES_SET=false
ENV CONFIG_SESSION_CONTROL_HANDLERS_MESSAGES_UPSERT=false
ENV WEBHOOK_GLOBAL_ENABLED=false

# ACESSO
ENV AUTHENTICATION_API_KEY=Wesley123!
ENV CORS_ORIGIN="*"

EXPOSE 10000

CMD ["node", "dist/src/main.js", "--port", "10000"]
