FROM atendai/evolution-api:latest

# Porta obrigatória da Render
ENV PORT=10000
ENV SERVER_PORT=10000

# CONFIGURAÇÃO DE BANCO DE DADOS (PADRÃO V2)
ENV DATABASE_ENABLED=true
ENV DATABASE_CONNECTION_PROVIDER=sqlite
ENV DATABASE_CONNECTION_URI="file:/evolution/store/data.db"

# PERFORMANCE
ENV DATABASE_SAVE_DATA_INSTANCE=true
ENV DATABASE_SAVE_DATA_CHATS=false
ENV DATABASE_SAVE_DATA_CONTACTS=false
ENV DATABASE_SAVE_DATA_MESSAGES=false

# SEGURANÇA E ACESSO
ENV AUTHENTICATION_API_KEY=Wesley123!
ENV CORS_ORIGIN="*"

# Permissões
USER root
RUN mkdir -p /evolution/store && chmod -R 777 /evolution/store

EXPOSE 10000

CMD ["node", "dist/src/main.js"]
