FROM atendai/evolution-api:v1.8.2

ENV PORT=10000
ENV SERVER_PORT=10000

# CONFIGURAÇÃO DE CONEXÃO LEVE (Evita o erro no celular)
ENV DATABASE_TYPE=sqlite
ENV DATABASE_SAVE_DATA_INSTANCE=true
ENV DATABASE_SAVE_DATA_CHATS=false
ENV DATABASE_SAVE_DATA_CONTACTS=false
ENV DATABASE_SAVE_DATA_MESSAGES=false

# Segurança e Permissões
ENV AUTHENTICATION_API_KEY=Wesley123!
ENV CORS_ORIGIN="*"

EXPOSE 10000

CMD ["node", "dist/src/main.js", "--port", "10000"]
